name: 🐛 Bug report
description: Report a bug to help us improve Dex
body:
- type: input
  attributes:
    label: Version
    description: What version of Dex are you running? It will be one of the versions in https://github.com/maelvls/google-to-synology-sso/releases
    placeholder: 2.29.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior if it is not self-explanatory.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  attributes:
    label: Additional Information
    description: Links? References? Anything that will give us more context about the issue that you are encountering!
- type: textarea
  attributes:
    label: Configuration
    description: Contents of your configuration file (if relevant).
    render: yaml
    placeholder: |
      issuer: http://127.0.0.1:5556/dex

      storage:
        # ...

      connectors:
        # ...

      staticClients:
        # ...
- type: textarea
  attributes:
    label: Logs
    description: Dex application logs (if relevant).
    render: shell
